export const CONST_URL_APPLIED = 'https://randomuser.me/api/?nat=gb&results=5';

export const TYPE_APPLIED_USERS_SUCCESS = 'TYPE_APPLIED_USERS_SUCCESS';
export const TYPE_APPLIED_USERS_REMOVE = 'TYPE_APPLIED_USERS_REMOVE';
export const TYPE_APPLIED_USERS_ADD = 'TYPE_APPLIED_USERS_ADD';

export const TYPE_INTERVIEWING_USERS_ADD = 'TYPE_INTERVIEWING_USERS_ADD';
export const TYPE_INTERVIEWING_USERS_REMOVE = 'TYPE_INTERVIEWING_USERS_REMOVE';

export const TYPE_HIRED_USERS_ADD = 'TYPE_HIRED_USERS_ADD';
export const TYPE_HIRED_USERS_REMOVE = 'TYPE_HIRED_USERS_REMOVE';
